### ISSUE TITLE
Site from plugin header is not working

### ISSUE THREAD

**Issue by dimadin** [easydigitaldownloads/pushover-notifications-edd-ext#20]
`http://wp-push.com` is in both "Author URI" and "Plugin URI", but that site gives an error.

Also, link should be updated to HTTPS version.

**Comment by robincornett** [comment]
@ashleyfae the plugin header was updated in #28, so the extension is now as correct as we can make it--I think this can be closed. I did let @cklosowski know that the wp-push site was down so he is aware.

**Comment by ashleyfae** [comment]
Yep, looks like you're right @robincornett :+1:
