### ISSUE TITLE
Fatal error after deactivating other plugins

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/pushover-notifications-edd-ext#30]
I deactivated a handful of other plugins and one of them was evidently masking a bug I introduced in fixing #28. I'm getting this error:

> Fatal error: Uncaught Error: Call to undefined function get_plugins()
in \wp-content\plugins\pushover-notifications-edd-ext\pushover-notifications-edd-ext.php on line 84

The `checkCoreVersion` method uses `get_plugins`, but in that PR, I removed the line before the class which loads the `plugin.php` file:

```php
include_once ABSPATH . 'wp-admin/includes/plugin.php';
```

Adding that back to that method does fix the error, but it kind of feels like not a great way to do the job.

Wondering if we could just do an admin notice if the core version is not met, and then use a standard `function_exists` for something in the primary Pushover plugin to manage preventing this extension from running.

**Comment by robincornett** [comment]
@cklosowski I'm looking at the Pushover Notifications repository and can't tell if you introduced a new function in version 1.9.3, which would be my personal preferred way to do this--maybe `ckpn_get_users_with_keys` (because the changelog says "NEW/FIX: Setting for a list of all users with Pushover Keys in their profile (helps with performance, thanks Pippin)" for that version)? If you have a chance and can weigh in, that would be great--otherwise I'll do the easier fix.

**Comment by cklosowski** [comment]
@robincornett you can likely change it to be the fix you want. I had to add these version checks in for things. This was before a lot of plugins were doing interdependant dependency checks. Back then it was the standard way to handle this.

I'm okay with whatever you choose ,but I don't have a 'new' way to do this.
