### ISSUE TITLE
Constant admin nag because for update

### ISSUE THREAD

**Issue by mihaijoldis** [easydigitaldownloads/pushover-notifications-edd-ext#33]
Tested on the 1.3.3 branch as I think that will be the next release and I still got it.

```
		$pushover_version = defined( 'CKPN_VERSION' ) ? CKPN_VERSION : false;
		if ( ! $pushover_version || version_compare( $pushover_version, '1.9.3', '<' ) ) {
```
Because of that the nag will always show fromw what I can tell.
`CKPN_VERSION` is not defined so first condition runs always

**Comment by mihaijoldis** [comment]
This has been reported by a customer https://secure.helpscout.net/conversation/1604698347/192023?folderId=180499

**Comment by ashleyfae** [comment]
This plugin requires that you also have the `Pushover Notifications` plugin installed. Do you have that installed @mihaijoldis ? If it's not installed then `CKPN_VERSION` will be undefined and you _should_ get a notice about that.

**Comment by mihaijoldis** [comment]
Well I did not lol and neither does the customer now that you mentioned it. Will tell him to install it!
