### ISSUE TITLE
Move sales notifications to a wp_cron

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/pushover-notifications-edd-ext#9]
If a site has lots of keys entered or makes lots of sales, sending pushover notifications as a payment completes can slow down the processing of a purchase

We could schedule a 1 time event for a payment made that fires with wpcron ~1 minute later that does the looping to send notifications since these aren't time sensitive to the second. Might help with processing speed.

**Comment by cklosowski** [comment]
This is doubly so with commissions enabled

**Comment by pippinsplugins** [comment]
I like this plan.

**Comment by cklosowski** [comment]
Requires the work going on in EDD Core `issue/5453` (but `release/2.8` in the future).
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5453

**Comment by cklosowski** [comment]
`release/2.8` is in beta, so this branch can get pushed off to it.
